version: "3" 

services: 
  api:
    build:
      context: ./api/
      dockerfile: dockerfile
      args: 
        UID: 1000 
        GID: 1000 
    container_name:  kouiz-back
    hostname: kouiz-back
    restart:  always
    ports:
      - 8000:8000
    volumes:
      - ./api/:/app
      - ./api/.env:/app/.env

  db: 
    image: mariadb:10.3.9
    container_name: db-kouiz
    hostname: db-kouiz
    restart: always
    env_file:
      - .env
    volumes:
      - ../db-kouiz:/var/lib/mysql 
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    hostname: phpmyadmin
    env_file:
      - .env
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_HOST=${DB_HOST}
      - PMA_PORT=${DB_PORT}
      # - PMA_USER=${DB_USERNAME}
      # - PMA_PASSWORD=${DB_PASSWORD}

  react:
    build:
      context: ./app/
      dockerfile: dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./app:/app

# volumes:
#   api: 